name: Send Code Diff to Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed lines (diff) and save to file
        id: git_diff
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            DIFF_TEXT=$(git diff-tree -r -p --no-commit-id HEAD | grep -E "^[+-][^+--]" | head -n 500)
          else
            DIFF_TEXT=$(git diff ${{ github.event.before }} HEAD | grep -E "^[+-][^+--]" | head -n 500)
          fi
          
          if [ -z "$DIFF_TEXT" ]; then
            DIFF_TEXT="Нет текстовых изменений в коде"
          fi
          
          echo "$DIFF_TEXT" > changes.diff

      - name: Send to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Akane Coder"
          content: |
            **Новый коммит от ${{ github.actor }}!**
            📝 *Комментарий:* ${{ github.event.head_commit.message }}
          filename: changes.diff
