name: Send Code Diff to Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed lines (diff) and save to file
        id: git_diff
        run: |
          # Собираем измененные строки (увеличили лимит до 500 строк, чтобы влезло всё)
          DIFF_TEXT=$(git diff HEAD~1 HEAD | grep -E "^[+-][^+--]" | head -n 500)
          
          if [ -z "$DIFF_TEXT" ]; then
            DIFF_TEXT="Нет текстовых изменений в коде"
          fi
          
          # Записываем изменения в файл с расширением .diff для цветной подсветки
          echo "$DIFF_TEXT" > changes.diff

      - name: Send to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Akane Coder"
          content: |
            **Новый коммит от ${{ github.actor }}!**
            📝 *Комментарий:* ${{ github.event.head_commit.message }}
          filename: changes.diff
